In [1]:
#import liberies
import numpy as np

# Basics

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# get shape

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
#get type

print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
#Get size

print(a.itemsize)
print(b.itemsize)

4
4


In [8]:
#get total size
print(a.size)
print(b.size)


3
6


In [9]:
# get byte size
a.size * a.itemsize

# another way

a.nbytes

12

In [10]:
# another initialize value

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# shape

a.shape


(2, 7)

In [12]:
#Get a specific element (r, c) remember start with 0;

a[1, 4]


12

In [13]:
# Get specific row

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get specific colum
a[ : , 4 ]

array([ 5, 12])

In [15]:
#Getting a lilte more [row, startingindex:endingindex:step(size)]

a[1, 1:6:2]

array([ 9, 11, 13])

In [16]:
#Change row value
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
#change colum value 

a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3d example

In [18]:
b=np.array([[[1,2],[7,3]],[[4,5],[5,6]]])
print(b)

[[[1 2]
  [7 3]]

 [[4 5]
  [5 6]]]


In [19]:
#get specific value

b[0,1,1]


3

In [20]:
#get colum value[row number:innerRow: valueindex]

b[:,1,:]

array([[7, 3],
       [5, 6]])

In [21]:
#change value
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[4 5]
  [8 8]]]


# initializing diferent types of array

In [22]:
#All 0's martix((dimention,rownumber,columnumber))

np.zeros((2,6,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
#All 1's matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
#any all others
np.full((2,2),77,dtype="float32")

array([[77., 77.],
       [77., 77.]], dtype=float32)

In [25]:
#any other number full_like a we initial
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
#Random decemal number

np.random.rand(4,2)

array([[0.89330044, 0.09908866],
       [0.79054701, 0.25293003],
       [0.02559861, 0.44548421],
       [0.21864098, 0.73644246]])

In [27]:
#Random shape 

np.random.random_sample(a.shape)

array([[0.35159124, 0.75974885, 0.94662862, 0.455564  , 0.32040904,
        0.0097332 , 0.41262507],
       [0.95418793, 0.76611282, 0.82162121, 0.80994279, 0.70979098,
        0.09725257, 0.23214946]])

In [28]:
#Random interger number

np.random.randint(4,7, size=(3,3))

array([[6, 4, 4],
       [6, 5, 4],
       [4, 6, 4]])

In [29]:
#identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#repeater array

arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
#repeater array

arr=np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [32]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [34]:
#replace the value of ouput matrix with z matrix

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# some diferent

In [35]:

a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


In [36]:
#copy array
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [37]:
print(b)

[100   2   3]


# Mathematics

In [38]:
a+2

array([3, 4, 5])

In [39]:
a-2

array([-1,  0,  1])

In [40]:
a*2

array([2, 4, 6])

In [41]:
a/2

array([0.5, 1. , 1.5])

In [42]:
b=np.array([1,2,3])
a+b

array([2, 4, 6])

In [43]:
a**2

array([1, 4, 9], dtype=int32)

In [44]:
#take the sin

np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [45]:
#take the cos

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# linear algebra

In [46]:
a=np.ones([2,3])
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [47]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [48]:
#find the determinat

c=np.identity(3)
np.linalg.det(c)

1.0

# statistics

In [49]:
stat=np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.min(stat)

1

In [51]:
np.max(stat)

6

In [52]:
np.min(stat, axis=0)

array([1, 2, 3])

In [53]:
np.max(stat, axis=1)

array([3, 6])

# Reorganizing Array

In [54]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [55]:
#vertically stocking array

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [56]:
#horizantali stocking array

np.hstack([v1,v2,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8])

# load data from file

In [57]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata

array([[ 2., 24., 35., 65., 78.,  4.,  5.,  6.,  7., 24., 56., 78., 45.],
       [56., 78.,  5., 45., 65., 33., 43., 56., 76., 45., 34., 23., 12.]])

# boolean mask and advance index

In [58]:
filedata>50

array([[False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False],
       [ True,  True, False, False,  True, False, False,  True,  True,
        False, False, False, False]])

In [59]:
filedata[filedata>50]

array([65., 78., 56., 78., 56., 78., 65., 56., 76.])

In [60]:
filedata=filedata.astype("int32")

In [61]:
filedata

array([[ 2, 24, 35, 65, 78,  4,  5,  6,  7, 24, 56, 78, 45],
       [56, 78,  5, 45, 65, 33, 43, 56, 76, 45, 34, 23, 12]])

In [62]:
#index list in numpy


a=np.array([1,2,3,4,5,6,7,8,9])

a[[1,3,8]]

array([2, 4, 9])

In [63]:
((filedata>50) & (filedata<100))

array([[False, False, False,  True,  True, False, False, False, False,
        False,  True,  True, False],
       [ True,  True, False, False,  True, False, False,  True,  True,
        False, False, False, False]])

In [64]:
filedata[((filedata>50) & (filedata<100))]

array([65, 78, 56, 78, 56, 78, 65, 56, 76])

####################################################THANKS#####################################################################